import dts from 'rollup-plugin-dts';

export default {
    input: './dist/index.d.ts', // TypeScript declarations generated by tsc
    output: {
        file: './dist/index.d.ts', // Flattened type declaration file
        format: 'es',
    },
    plugins: [dts()],
};